boot.o: boot.S multiboot.h x86_desc.h types.h
syscall_handler.o: syscall_handler.S
wrappers.o: wrappers.S
x86_desc.o: x86_desc.S x86_desc.h types.h
exceptions.o: exceptions.c exceptions.h lib.h types.h
fs.o: fs.c fs.h lib.h types.h syscalls.h x86_desc.h terminal.h i8259.h \
  rtc.h tasks.h paging.h
i8259.o: i8259.c i8259.h types.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  rtc.h syscalls.h terminal.h tasks.h paging.h fs.h exceptions.h
lib.o: lib.c lib.h types.h terminal.h i8259.h syscalls.h x86_desc.h rtc.h \
  tasks.h paging.h fs.h
paging.o: paging.c paging.h types.h terminal.h lib.h i8259.h syscalls.h \
  x86_desc.h rtc.h tasks.h fs.h
rtc.o: rtc.c rtc.h lib.h types.h i8259.h syscalls.h x86_desc.h terminal.h \
  tasks.h paging.h fs.h
syscalls.o: syscalls.c syscalls.h lib.h types.h x86_desc.h terminal.h \
  i8259.h rtc.h tasks.h paging.h fs.h
terminal.o: terminal.c terminal.h lib.h types.h i8259.h syscalls.h \
  x86_desc.h rtc.h tasks.h paging.h fs.h
